name: how_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  custom_refresh_indicator: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.7.0
  envied: ^1.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.6.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.20.1
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  talker: ^4.6.1
  talker_dio_logger: ^4.6.1
  talker_flutter: ^4.6.1
  vector_graphics: ^1.1.19

dev_dependencies:
  bloc_test: ^9.1.7

  # Code Generation
  build_runner: ^2.4.14

  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/

# FlutterGen: run this command:
# $ dart pub global activate flutter_gen
# $ fluttergen -h
# $ fluttergen -c example/pubspec.yaml
flutter_gen:
  output: lib/core/ui/generated
  line_length: 80
  integrations:
    flutter_svg: true
